export type PipelineStage = "lead" | "deal" | "install" | "cancelled";

export type TapeCustomer = {
  id: number;
  tapeRecordId: number;
  pid: string | null;
  customerName: string | null;
  customerAddress: string | null;
  customerCity: string | null;
  customerState: string | null;
  customerZip: string | null;
  customerEmail: string | null;
  customerPhone: string | null;
  productName: string | null;
  grossAccountValue: number | null;
  jobStatus: string | null;
  ntpAppStatus: string | null;
  kw: number | null;
  netEpc: number | null;
  sowAmount: number | null;
  notes: string | null;
  saleDate: string | null;
  cancelDate: string | null;
  installCompletedDate: string | null;
  closer1: string | null;
  setter1: string | null;
  closer2: string | null;
  division: string | null;
  region: string | null;
  team: string | null;
  officeName: string | null;
  state: string | null;
  market: string | null;
  pipelineStage: PipelineStage;
  hasInstall: boolean;
  syncedAt: string;
};

export type TapeCustomerRow = {
  id: number;
  tape_record_id: number;
  pid: string | null;
  customer_name: string | null;
  customer_address: string | null;
  customer_city: string | null;
  customer_state: string | null;
  customer_zip: string | null;
  customer_email: string | null;
  customer_phone: string | null;
  product_name: string | null;
  gross_account_value: number | null;
  job_status: string | null;
  ntp_app_status?: string | null;
  kw: number | null;
  net_epc: number | null;
  sow_amount: number | null;
  notes: string | null;
  sale_date: string | null;
  cancel_date: string | null;
  install_completed_date?: string | null;
  closer_1: string | null;
  setter_1: string | null;
  closer_2: string | null;
  division?: string | null;
  region?: string | null;
  team?: string | null;
  office_name?: string | null;
  state?: string | null;
  market?: string | null;
  dealer_name?: string | null;
  pipeline_stage?: PipelineStage | null;
  has_install?: boolean | null;
  raw_tape: unknown;
  synced_at: string;
};
